### PR TITLE
05 coders choice dev

### PR DESCRIPTION
**Pull request by shashitekula**
Hi professor,

Name - Shashi Tekula
ID - 46739619

As per your recommendation, implement "Simple_one_for_one".
if you notice code base , i have coded for one_for_one which has state as list of maps to support multi user scenario.
I could modify to support "Simple_one_for_one" but would lead to just one user only per PID.
Please advise if you still want me to proceed ?

Thanks
Shashi Tekula

### CODE REVIEW

**Comment by pragdave** [comment]
I like the little refactorings you are doing as you go along.

Right now, I don't see you ever updating the state—the Service.Server `handle_` functions always return the same state they were passed. So I'm not sure why this is even a server.

**Comment by shashitekula** [comment]
Hi Professor,

I just reviewed the state logic , its appears to be working as expected and the state is been updated.

Executed below command after  - 

- > iex -S mix


PasswordApp.create({"Shashi1use", "Shashi1pas"})
PasswordApp.create({"Shashi2use", "Shashi2pas"})
Agent.get(PasswordApp.Store.Server, fn x -> x end)
PasswordApp.reset({"Shashi1use", "Shashi1pas", "Shashi1cha"})

Agent.get(PasswordApp.Store.Server, fn x -> x end)
I do see the state has updated with new password.

screen shot 2017-11-24 at 1 16 11 pm


Thanks
Shashi Tekula

**Comment by shashitekula** [comment]
Hi Professor,

I just reviewed the state logic , its appears to be working as expected and the state is been updated.

Executed below command after -

  *
iex -S mix

PasswordApp.create({"Shashi1use", "Shashi1pas"})
PasswordApp.create({"Shashi2use", "Shashi2pas"})
Agent.get(PasswordApp.Store.Server, fn x -> x end)
PasswordApp.reset({"Shashi1use", "Shashi1pas", "Shashi1cha"})

Agent.get(PasswordApp.Store.Server, fn x -> x end)
I do see the state has updated with new password.

[cid:D3672074-3DFE-4B96-B6AA-C457FC011180@corpaa.aa.com]



On Nov 24, 2017, at 11:42 AM, Dave Thoms <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the little refactorings you are doing as you go along.

Right now, I don't see you ever updating the state—the Service.Server handle_ functions always return the same state they were passed. So I'm not sure why this is even a server.

**Comment by pragdave** [comment]
The state is not being held in the server.

On Fri, Nov 24, 2017 at 1:29 PM, shashitekula <notifications@github.com> wrote:
Hi Professor,

I just reviewed the state logic , its appears to be working as expected and the state is been updated.

Executed below command after -

*
iex -S mix

PasswordApp.create({"Shashi1use", "Shashi1pas"})
PasswordApp.create({"Shashi2use", "Shashi2pas"})
Agent.get(PasswordApp.Store.Server, fn x -> x end)
PasswordApp.reset({"Shashi1use", "Shashi1pas", "Shashi1cha"})

Agent.get(PasswordApp.Store.Server, fn x -> x end)
I do see the state has updated with new password.

[cid:D3672074-3DFE-4B96-B6AA-C457FC011180@corpaa.aa.com]



On Nov 24, 2017, at 11:42 AM, Dave Thoms <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the little refactorings you are doing as you go along.

Right now, I don't see you ever updating the state—the Service.Server handle_ functions always return the same state they were passed. So I'm not sure why this is even a server.

**Pull request closed without merging**
