### PR TITLE
05 coders choice local - Sanity Check #2

### PR DESCRIPTION
**Pull request by jdavault**
I spent the past several days reading and re-reading the Programming Phoenix eBook and getting the rumbl app running.  It has god instruction on Ecto, repositories, and db relationships.   My app was working yesterday but it not working after my changes today, so I'm sending over the working rumbl app as my reference point / sanity check.  My app will be following very closely this example exception I'm going to try to separate out the repo app like we did in class (they don't do that in the book).

Joe

### CODE REVIEW

**Comment by pragdave** [comment]
Joe:

I need to you cite code that you've copied in from elsewhere. Otherwise I won't be able to give a grade. This applies to code copied as is and also to cope copied in and then modified.

**Comment by jdavault** [comment]
All of the code comes from the "rumbl" app in the Programming Phoenix
Book.  Granted mostly their code is generated from the models and html
builder and then modified but it is there code.  I ran the html and model
generators myself on my local app to create the MVC models and views and
CRUD operations based on what I read.  I can do a pull request and send you
that.

I had the code written following the example I saw in the Programming Phoenix book but my html helpers (e.g. xxx_path) were breaking.  I found while testing today that was from not having "resources /xxxx, XxxxController in my routes.ex.  I have the products and cart models, views and CRUD operations in place now and am wiring up the ecto today.   My code is far from complete but this was meant to show my direction and thus serve as my sanity check.
 
Joe

**Comment by pragdave** [comment]
I just need you to flag files that are not all your own work. You don’t need to do this with files created by `mix new` or `mix phx.new`, for for the rest, I need a clear indication that this is not your original work. Without this, I’d have to grade the project a 0.
Dave Thomas

On Fri, Nov 24, 2017 at 11:16 AM, Joe Davault <notifications@github.com> wrote:
All of the code comes from the "rumbl" app in the Programming Phoenix
Book. Granted mostly their code is generated from the models and html
builder and then modified but it is there code. I ran the html and model
generators myself on my local app to create the MVC models and views and
CRUD operations based on what I read. I can do a pull request and send you
that.

Joe

**Comment by jdavault** [comment]
I added references ... to my pull request.  I borrowed from several
sources, including class.  I have once class left to take an your and your
class have been the worst experience.  You teach on thing and then grade on
something else entirely .. I've done best i can in your class ... do
whatever your conscious tells you todo but dont think the university is not
going to get earful from me.  Have a good life dave.  You wont be seeing me
again.

Joe

**Pull request closed without merging**
