### PR TITLE
justin - check-in 2

### PR DESCRIPTION
**Pull request by justinledford**
Justin Ledford
28148527

Since last time:
A lot of refactoring
Distributed node support

I thought about using a single stream for password candidates like we discussed but then realized take_every would still generate the intermediate elements, losing the benefit of splitting up the work between workers. Maybe there is another way, but for now I'm still just creating separate streams for each worker.

I have an option now in the CLI that takes a list of worker nodes, and then workers are split up evenly among the nodes. There may be a better way of organizing the processes but for now its like this:

```
          Dispatcher            (GenServer)
              |
              v
     DispatcherSupervisor       (Supervisor)
     /     |     |     \
     v     v     v     v
Worker1 Worker2 Worker3 Worker4 (GenServer)
     |     |     |     |
     v     v     v     v
   Node1 Node2 Node1 Node2      (Process)

```
The processes are just spawned using Node.spawn_link, but maybe it would make more sense
to have each node have its own supervisor and workers are started under those supervisors.

I was able to run this on my home network with nodes on my laptop and desktop. I was also able
to get Elixir and Erlang running on the supercomputer and ran this on nodes with 256 cores.

Brute forcing the string "foob" as a sha256 hash took 41s with 1 worker but 3s with 64 workers!

Look at the real vs user time when cracking "fooba":
```
[jledford@tk002 client]$ time ./hashcracker -h "41cbe1a87981490351ccad5346d96da0ac10678670b31fc0ab209aed1b5bc515" -t sha256 -n 64 -a brute
Password found: fooba

real    0m38.003s
user    38m2.186s
sys     0m4.216s
```
So basically it would have taken 38+ min with 1 worker.

With 4 nodes and 64 workers, I'm only seeing a 15% speedup, but I'm thinking this is because each node isn't using the peak number of workers it can handle (brute/mask are limited by the max number of characters in the first position of the mask which is 88 for all letters, numbers, and symbols, a good
reason to try again with the single stream to split it by any arbitrary number).

The dictionary attack doesn't have this limit because it just opens the file and seeks to its own section of
the file for each worker and it has a bit of a better speed between 1 node with 512 workers and
4 nodes with 512 workers. 

To wrap up this project I'm going to see if I can improve the server/supervisor/process structure, have
the workers send back progress (# of hashes computed) to the client, and see if it would be beneficial
to backup the streams for each worker in case any of them crash.

### CODE REVIEW

**Comment by pragdave** [comment]
Just as a matter of interest, on your home network, are the times for 2 node/32 workers better or worse than the one node and/or four node times? I'm guessing you're not maxing out the cpus.

**Comment by justinledford** [comment]
With 2 nodes (separate computers), I'm seeing that its better than 1 node.

I'm still trying to think of how to split up a stream without any bound on the number of splits so I can have more workers per node. The main issue is that the stream depends on previous elements to evaluate, so I have to split it before, otherwise I'm thinking the nodes will still evaluate any previous dropped elements.

For example if I have the input as [ ["a", "b"], ["c", "d" ], ["e", "f"] ], the output will be:
[["a", "c", "e"], ["b", "c", "e"], ["a", "d", "e"], ["b", "d", "e"],
 ["a", "c", "f"], ["b", "c", "f"], ["a", "d", "f"], ["b", "d", "f"]]. 

So to split it up I'm doing the same operations but with inputs  [ ["a"], ["c", "d" ], ["e", "f"] ] and  [ ["b"], ["c", "d" ], ["e", "f"] ]. Otherwise if I try to take_every or some combination of take and drop, I think it will still evaluate unneeded elements (unless those elements are implicitly shared between processes/nodes??), because to compute ["a", "c", "e"], we need ["a", "c"]. So the bound of splits/workers now is the number of elements in that first enum. I could continue splitting the next enums, but I think that will start getting messy.

**Comment by pragdave** [comment]
On Sat, Nov 25, 2017 at 5:33 PM, justinledford <notifications@github.com> 
wrote:
For example if I have the input as [ ["a", "b"], ["c", "d" ], ["e", "f"] ], 
the output will be:

[["a", "c", "e"], ["b", "c", "e"], ["a", "d", "e"], ["b", "d", "e"],
["a", "c", "f"], ["b", "c", "f"], ["a", "d", "f"], ["b", "d", "f"]].


What if you had a stream that could be started at any position of the 
permutation:
https://gist.github.com/pragdave/721e9844d6f8e20e2aec3c3544e694f9 
[https://gist.github.com/pragdave/721e9844d6f8e20e2aec3c3544e694f9]
(this blows up if you ask it to go past the end, but otherwise seems to 
work)
You could then create a separate stream for each worker.

**Comment by justinledford** [comment]
Thanks this is awesome! I'm going to see if I can incorporate this tonight.

**Pull request closed without merging**
