### PR TITLE
Homework Board - Final Project Submission

### PR DESCRIPTION
**Pull request by kellenschmidt**

### CODE REVIEW

**Comment by kellenschmidt** [comment]
Name: Kellen Schmidt
SMU ID: 46815383

**Comment by pragdave** [comment]
Very nice looking....

When I try to create a new assignment, I get

~~~
no function clause matching in FrontendWeb.NewAssignmentController.format_map_with_ints/1
~~~

same when I try to create a tag. I had to manually add a row to the columns table.

There is a bug when you create or edit assignment. If successful, you just render the index. The problem with this is if I reload the page, it adds the assignment again. You should redirect,

Some tests would have boosted your grade :)

Finally, the controllers are a little bit "fat"—there are a lot of helper functions in there. Ideally these should be split out. That way you can reuse things like `map_keys_from_string_to_atom`.

Anyway, this was a good, solid (and nice looking) project. Thank you.

**Comment by kellenschmidt** [comment]
Thank you, Professor!

With regard to the error
```
no function clause matching in FrontendWeb.NewAssignmentController.format_map_with_ints/1
```
did you execute the command `mix run priv/repo/seeds.exs` before running the application as specified in step 5 of the "Running project locally" section of the README file?

This elixir script creates 3 columns in the "Columns" database so there wouldn't be any errors.

Let me know and thanks for the feedback!

Sincerely,
Kellen Schmidt

**Comment by pragdave** [comment]
Oops, I missed that. Don't worry, that issue didn't cost you any marks.

**Pull request closed without merging**
