### PR TITLE
Coder's Choice Proposal

### PR DESCRIPTION
**Pull request by jdavault**
Here is my proposal

Joe Davault
ID: 46360344

### CODE REVIEW

**Comment by pragdave** [comment]
Joe: apart from the database, how will this be different to Assignment 4?

**Comment by jdavault** [comment]
That's valid skepticism .. they would be similar.  To that I would say most
apps follow the same general CRUD, MVC approach with the following layers



·         UI/Web Component (or app)

·         Model (business logic)

·         Repo Component (or app)

·         Supervising the Model and repo components



Instead of hangman app, I’ll can instead do a shopping cart and have a
order history page to see the orders placed.  Would that create enough
distinction between the previous assignments?


Regards,


Joe

**Comment by pragdave** [comment]
I guess I was confused by the implication that Assignment 4 wasn’t an MVC-style implementation. I’m anxious to give you the best possible start to this project, and I think it would help to spell out explicitly what you mean.

On Mon, Nov 6, 2017 at 11:39 AM, Joe Davault <notifications@github.com> wrote:
That's valid skepticism .. they would be similar. To that I would say most
apps follow the same general CRUD, MVC approach with the following layers



· UI/Web Component (or app)

· Model (business logic)

· Repo Component (or app)

· Supervising the Model and repo components



Instead of hangman app, I’ll can instead do a shopping cart and have a
order history page to see the orders placed. Would that create enough
distinction between the previous assignments?


Regards,


Joe

**Comment by jdavault** [comment]
In Hangman assignment we had a data layer (the file based dictionary), an
API layer, hangman and a “GUI” layer, human_player, so if I did the Phoenix
version of Hangman, most of the changes would really be in converting the
human_player to Phoenix web app.  The rest would not change much .. I
thought of getting my data in a different way to mix it up..  If that is
too similar, I will instead create a simple shoppingCart comprised of a web
tier, a model tier and data tier using postgres.  With the model and data
tier coming under OTP supervision.


Joe

**Comment by pragdave** [comment]
Oh, you’re right. In my head we’d done a web based Hangman.
So, now my problem is that we can’t count the Hangman code itself towards the assignment, because you’ll be using it unchanged. And I doubt there’ll be a sufficient number of lines of code in the rest.
So let’s go with the shopping cart.
Approved.

On Mon, Nov 6, 2017 at 12:02 PM, Joe Davault <notifications@github.com> wrote:
In Hangman assignment we had a data layer (the file based dictionary), an
API layer, hangman and a “GUI” layer, human_player, so if I did the Phoenix
version of Hangman, most of the changes would really be in converting the
human_player to Phoenix web app. The rest would not change much .. I
thought of getting my data in a different way to mix it up.. If that is
too similar, I will instead create a simple shoppingCart comprised of a web
tier, a model tier and data tier using postgres. With the model and data
tier coming under OTP supervision.


Joe

**Comment by jdavault** [comment]
Very good!  I'm glad you pressed.  Now that I think about it more, I would
rather do a shopping cart with a back end database (that more in my
wheelhouse).  By drawing from the board and notebook examples (Phoenix and
MVC) and OTP from hangman, it should be manageable yet enjoyable assignment.

Regards,

Joe

**Comment by pragdave** [comment]
# Approved

**Pull request closed without merging**
